server:
  port: 8081

spring:
  mail:
    host: smtp.qq.com
    username: 2051912363@qq.com
    password: eganvcrbntroeccd
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465
    properties.mail.display.sendmail: plum
    properties.mail.display.sendname: huangmeiximi
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.4.201.7:3306/plum?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: Huang3
    password: Huangzi3$

  session:
    store-type: jdbc
    timeout: 2592000

mybatis:
  mapper-locations: classpath:mapper/*.xml